# Generated by Django 2.2.4 on 2021-02-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='students',
        ),
        migrations.AddField(
            model_name='ninja',
            name='assigneddojo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ninjas_app.Dojo'),
        ),
    ]
