# Generated by Django 2.2.4 on 2021-02-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas_app', '0002_auto_20210219_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
